# Generated by Django 2.0.4 on 2018-08-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(max_length=4)),
                ('order_number', models.CharField(max_length=11)),
                ('pro_num', models.CharField(max_length=12)),
                ('pro_name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=10, null=True)),
                ('p_size', models.CharField(max_length=40, null=True)),
                ('plan_start', models.CharField(max_length=8, null=True)),
                ('plan_end', models.CharField(max_length=8, null=True)),
                ('reality_time', models.CharField(max_length=8, null=True)),
                ('stat_code', models.CharField(max_length=1, null=True)),
                ('batch', models.CharField(max_length=20, null=True)),
                ('into_count', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
            ],
        ),
    ]
