# Generated by Django 2.0.4 on 2018-08-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repertory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstat',
            name='pro_name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='orderstat',
            name='pro_num',
            field=models.CharField(max_length=20),
        ),
    ]
