# Generated by Django 2.2.2 on 2020-01-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.GenericIPAddressField(verbose_name='用户')),
                ('from_host', models.CharField(max_length=20, verbose_name='远程地址')),
                ('user_visits', models.IntegerField(verbose_name='访问次数')),
                ('visits_url', models.TextField(verbose_name='访问url')),
                ('target', models.CharField(default='null', max_length=50, verbose_name='打分对象')),
                ('flag', models.CharField(max_length=1, verbose_name='成功码')),
                ('come_time', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='访问时间')),
                ('client', models.CharField(default='', max_length=6, verbose_name='客户端识别区分码')),
            ],
        ),
        migrations.AddField(
            model_name='vote',
            name='introduce',
            field=models.TextField(default='null', verbose_name='节目介绍'),
        ),
        migrations.AddField(
            model_name='vote',
            name='score',
            field=models.SmallIntegerField(default=0, verbose_name='得分'),
        ),
    ]
