# Generated by Django 2.2.2 on 2020-01-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_auto_20200113_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Start',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.IntegerField(default=0, verbose_name='start/stop')),
            ],
        ),
        migrations.AlterField(
            model_name='votes',
            name='score',
            field=models.IntegerField(default=0, verbose_name='得分'),
        ),
    ]
