# Generated by Django 2.0.4 on 2018-08-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=20)),
                ('close_year', models.CharField(max_length=4)),
                ('close_month', models.CharField(max_length=2)),
                ('currency', models.CharField(max_length=10)),
                ('source_bill', models.CharField(max_length=4)),
                ('department', models.CharField(max_length=4)),
                ('domestic_currency_borrow', models.DecimalField(decimal_places=2, max_digits=12)),
                ('domestic_currency_loan', models.DecimalField(decimal_places=2, max_digits=12)),
                ('uncleared_borrow', models.DecimalField(decimal_places=2, max_digits=12)),
                ('uncleared_loan', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_number', models.CharField(max_length=20)),
                ('depart_name', models.CharField(max_length=40)),
            ],
        ),
    ]
