# Generated by Django 2.0.4 on 2018-08-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceinfo',
            name='department',
            field=models.CharField(max_length=8),
        ),
    ]
