# Generated by Django 2.0.4 on 2018-07-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SellDirectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_date', models.DateField(null=True)),
                ('odd', models.CharField(max_length=20, null=True)),
                ('article', models.CharField(max_length=40, null=True)),
                ('art_num', models.CharField(max_length=20, null=True)),
                ('unit', models.CharField(max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('add1', models.CharField(max_length=100, null=True)),
                ('add2', models.CharField(max_length=100, null=True)),
                ('province', models.CharField(max_length=20, null=True)),
                ('consumer', models.CharField(max_length=50, null=True)),
                ('department', models.CharField(max_length=20, null=True)),
                ('staff', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellProxyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_date', models.DateField(null=True)),
                ('odd', models.CharField(max_length=20, null=True)),
                ('article', models.CharField(max_length=40, null=True)),
                ('art_num', models.CharField(max_length=20, null=True)),
                ('unit', models.CharField(max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('add1', models.CharField(max_length=100, null=True)),
                ('add2', models.CharField(max_length=100, null=True)),
                ('province', models.CharField(max_length=20, null=True)),
                ('proxy', models.CharField(max_length=50, null=True)),
                ('company', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
