# Generated by Django 2.2.2 on 2020-01-09 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='level',
            field=models.CharField(default='null', max_length=6),
        ),
    ]
