# Generated by Django 2.0.4 on 2018-06-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0002_auto_20180628_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selldirectinfo',
            name='add1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='selldirectinfo',
            name='add2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='selldirectinfo',
            name='article',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='selldirectinfo',
            name='company',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='selldirectinfo',
            name='data',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='selldirectinfo',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='selldirectinfo',
            name='province',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='selldirectinfo',
            name='proxy',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='selldirectinfo',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='selldirectinfo',
            name='unit',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sellproxyinfo',
            name='unit',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
