# Generated by Django 2.0.4 on 2018-07-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_date', models.DateField(null=True)),
                ('article', models.CharField(max_length=40, null=True)),
                ('art_num', models.CharField(max_length=20, null=True)),
                ('art_size', models.CharField(max_length=20, null=True)),
                ('unit', models.CharField(max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
            ],
        ),
    ]
