# Generated by Django 2.0.4 on 2018-07-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementinfo',
            name='art_size',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
