# Generated by Django 2.0.4 on 2018-07-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_auto_20180717_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementinfo',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='procurementinfo',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
