# Generated by Django 2.0.4 on 2018-07-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_auto_20180717_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementinfo',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='procurementinfo',
            name='total_price',
            field=models.DecimalField(decimal_places=4, max_digits=12, null=True),
        ),
    ]
