# Generated by Django 2.0.4 on 2018-08-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_auto_20180815_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementinfo',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True),
        ),
    ]
